services:
  db:
    container_name: postgresdb
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:rw
    networks:
      - orynet

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


  kratos-migrate:
    container_name: kratos-migrate
    image: oryd/kratos:v25.4.0

    environment:
      - DSN=postgres://dbuser:P@ssw0rd@postgresdb:5432/kratosdb?sslmode=disable
    command: ["migrate", "sql", "-ey"]
    networks:
      - orynet

    depends_on:
      - db


  kratos:
    container_name: kratos
    image: oryd/kratos:v25.4.0
    ports:
      - 4433:4433 # public
      - 4434:4434 # admin
    volumes:
      - ./kratos.yaml:/home/ory/kratos.yml
      - ./identity.default.schema.json:/etc/config/identity.default.schema.json
    environment:
      - DSN=postgres://dbuser:P@ssw0rd@postgresdb:5432/kratosdb?sslmode=disable
    command: ["serve", "--config", "/home/ory/kratos.yml"]
    networks:
      - orynet

    depends_on:
      - kratos-migrate



networks:
  orynet:
